### ISSUE TITLE
Error en MMHO_RWY_23.xml por fijo DUPUS

### ISSUE THREAD

**Issue by wichoesparza** [Vatmex/mexico-vatsys-sector#10]
Durante la creación de HMO se uso el AIRAC 2102 el cual remplaza DUPOS por DUPUS. Sin embargo se esta trabajando en AIRAC 2014 por lo que en el archivo MMHO_RWY_23.xml en la linea 14 olvide cambiar a DUPOS.

**Comment by hatoriganzo** [comment]
Muy mal @wichoesparza !
