### ISSUE TITLE
Perdida Radar secundario MEX ACC

### ISSUE THREAD

**Issue by wichoesparza** [Vatmex/mexico-vatsys-sector#11]
Todas las perdidas tuvieron una duración de +- 10 segundos

1. Perdida radar 10nm APN en UJ28 cruzando FL240 x2  
2. Perdida de radar fijo AVALI cruzando FL360 en la UT17 
3. 65-75nm E AVIVI en UT19
4. 10 W AVIVI a FL310 en la UT19
5. Perdida 25NE TMN FL340
6. Perdida radar sobre AVIVI FL370

**Comment by hatoriganzo** [comment]
Debe estar arreglado con la reforma de radares. En caso de presentarfallas de cobertura crear issues nuevos.
