### ISSUE TITLE
Frecuencia MMZT_CTR igual a MMID_CTR

### ISSUE THREAD

**Issue by enriquea88** [Vatmex/mexico-vatsys-sector#133]
Revisar el cambio de frecuencia compartida entre MMZT_CTR y MMID_CTR (128.300).

**Comment by wichoesparza** [comment]
Sectorización revisada.
![Sectores Apoyo](https://user-images.githubusercontent.com/69885717/174455107-0fa8a684-1e5f-42a1-84a9-8a268b112dd4.png)
![Sectores Combinado](https://user-images.githubusercontent.com/69885717/174455111-74d0b92a-8f65-45a9-9b9c-a45b79d7153d.png)
