### ISSUE TITLE
Review unused Fixes

### ISSUE THREAD

**Issue by hatoriganzo** [Vatmex/mexico-vatsys-sector#191]
Review valid and current but unused fixes:

- AMEVI
- APRIM (AIF ILSZ29 MMGL)
- AVUGA (Possible MMAA Missed Approach)
- AXELO (AIF ILSZ29 MMGL)
- BENAX
- DUNIS
- FIELS
- LEROV
- MEMIE
- MUSOS (AIF RNP33 MMTO)
- NAGOS
- SEBED
- TADSI
- TRANA
- VIMSO

**Comment by ImSpeddy** [comment]
AMEVI is part of RNP-23 MMHO (Based off Jeppesen MMHO 12-2)
AVUGA is ILS3-10 MMAA Missed Approach (Based off Jeppesen MMAA 11-6)
BENAX is the IAF for MMSM ILS and RNP 04L (Based off Jeppesen 11-2 and 12-2)
Both APRIM and AXELO are MMGL ILSZ29 and RNPZ29 IAFs (Based off Jeppesen 11-6 and 12-2)
DUNIS is IAF for MMSM ILS22R, RNP22R, ILS22C and RNP22C (Jeppesen 12-4, 11-4, 12-3 and 11-3)

None of this fixes have labels beacuse they are not part of an STAR, but can be added.
