### ISSUE TITLE
Typo en posición Tulum Terrester TLSMC

### ISSUE THREAD

**Issue by pupini123** [Vatmex/mexico-vatsys-sector#220]
![Screenshot 2024-02-12 at 17 13 38](https://github.com/vatmex/vatmex-mmfr-sector/assets/139715647/90047370-9cd3-42d0-b29d-cc4657496e72)

Debe decir «Terrestre Tulum ».
Salu2 cali2

**Comment by hatoriganzo** [comment]
Arreglado en 65a35d43e7a8c2d495264f9e21431ef3dabc910b. Se implementara en 2313.
