### ISSUE TITLE
MMMX MVA altitude text missing

### ISSUE THREAD

**Issue by wichoesparza** [Vatmex/mexico-vatsys-sector#235]
![Sin título](https://github.com/vatmex/vatmex-mmfr-sector/assets/69885717/c0627fad-e8e3-41d1-9ffc-e146940b6f82)
![image](https://github.com/vatmex/vatmex-mmfr-sector/assets/69885717/e3c3e429-09e2-443e-b3db-cd58d562af54)

**Comment by enriquea88** [comment]
Corrected in #260
