### ISSUE TITLE
MMSM Error diagrama terrestre 

### ISSUE THREAD

**Issue by AviationDash** [Vatmex/mexico-vatsys-sector#266]
Falta de calles de rodajo abajo de H
![image_2024-09-03_213035054](https://github.com/user-attachments/assets/73740b04-ebb0-4813-aafd-839401e84c20)
![image_2024-09-03_213108486](https://github.com/user-attachments/assets/5e1f511e-44bf-4949-af15-30b3c7215985)

**Comment by enriquea88** [comment]
Corregido en airac-2409, commit 5daee26
