### ISSUE TITLE
Perdida de cobertura radar y AFV en MMTL

### ISSUE THREAD

**Issue by AviationDash** [Vatmex/mexico-vatsys-sector#267]
Vuelos que van a tulum, debajo de cierta altitud, normalmente los dejas de ver y los dejas de escuchar por completo, forzando a pasar a texto, fuera de esto, ni siquiera aparecen en el diagrama terrestre.

- Altitud cuando se pierde (2000FT or below)
- Radius donde se pierde: 
![image_2024-09-16_170938617](https://github.com/user-attachments/assets/8d3f0e58-a64b-4a1c-915a-07fe9dedf73d)

**Comment by enriquea88** [comment]
@AviationDash ¿Qué posición y frecuencia estabas utilizando cuando sucedió el incidente?

**Comment by hatoriganzo** [comment]
Comportamiento esperado debido a la lejania con radares actuales. Hasta actualización del PIA o confirmación de un nuevo radar en MMTL no se cambiara.

Cerrado Wontfix.

**Comment by AviationDash** [comment]
Ultima posicion donde note esto, fue en MMID_CTR
