### ISSUE TITLE
MMFR Squawk Validation exception

### ISSUE THREAD

**Issue by enriquea88** [Vatmex/mexico-vatsys-sector#61]
Error en branch airac-2106
Observado en posición MMUN_APP

**Plugins: Exception thrown in plugin MMFR Squawk Validation. Field not found: 'RadarTrack.CoupledFDR'.**

![Screenshot 2021-07-24 100943](https://user-images.githubusercontent.com/79779875/126873031-85d759bd-52bc-45c7-9cfc-955f89e33a72.jpg)

**Comment by hatoriganzo** [comment]
Arreglado en branch de trabajo.
