### ISSUE TITLE
Fijo erroneo ILS Z RWY 10

### ISSUE THREAD

**Issue by wichoesparza** [Vatmex/mexico-vatsys-sector#69]
Faltaba fijo GL622 y corregir fijo GL623 (Estaba GL523) Lo que causaba una linea hasta GL523 después de GL621 (Imagen Adjunta)
![MMGL](https://user-images.githubusercontent.com/69885717/132613012-0e18338e-57c6-45ef-8a14-21c138739abf.png)

**Comment by hatoriganzo** [comment]
Arreglo por la persona que lo creo. Que mágico momento
